### ISSUE TITLE
Contao 4.13 Kompatibilität?

### ISSUE THREAD

**Issue by saress** [inspiredminds/contao-news-categories-search#3] opened 2022-02-18 12:13 UTC
Hallo Fritz,

ich habe gerade versucht auf einem unserer Testhosts ein Update von 4.12.6 auf die 4.13.0 zu machen und erhalte dabei folgenden Fehler:

`
$ /usr/bin/php -q -dmax_execution_time=0 -dmemory_limit=-1 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=Europe/Berlin /home/www/home/staging-c413/web/contao-manager.phar.php composer require contao/manager-bundle=4.13.* contao/news-bundle=4.13.* contao/calendar-bundle=4.13.* contao/faq-bundle=4.13.* contao/comments-bundle=4.13.* contao/newsletter-bundle=4.13.* contao/listing-bundle=4.13.* --no-update --no-scripts --prefer-stable --sort-packages --no-ansi --no-interaction

/home/www/home/staging-c413/composer.json has been updated

# Process terminated with exit code 0
# Result: OK

$ /usr/bin/php -q -dmax_execution_time=0 -dmemory_limit=-1 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=Europe/Berlin /home/www/home/staging-c413/web/contao-manager.phar.php composer update alnv/catalog-manager alnv/catalog-manager-export alnv/catalog-manager-importer codefog/contao-mobile_menu codefog/contao-news_categories fritzmg/contao-news-sorting inspiredminds/contao-author-news inspiredminds/contao-news-categories-search inspiredminds/contao-sibling-navigation madeyourday/contao-rocksolid-custom-elements madeyourday/contao-rocksolid-frontend-helper oveleon/contao-component-style-manager oveleon/contao-cookiebar terminal42/contao-leads terminal42/contao-node terminal42/contao-root-protection terminal42/notification_center contao/manager-bundle contao/news-bundle contao/calendar-bundle contao/faq-bundle contao/comments-bundle contao/newsletter-bundle contao/listing-bundle contao/conflicts --with-dependencies --prefer-dist --no-dev --no-progress --no-ansi --no-interaction --optimize-autoloader --dry-run

Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires contao/calendar-bundle 4.13.* -> satisfiable by contao/calendar-bundle[4.13.0].
    - inspiredminds/contao-news-categories-search 1.2.0 requires symfony/dependency-injection ^3.2 || ^4.1.12 -> satisfiable by symfony/dependency-injection[v3.2.0, ..., v3.4.47, v4.1.12, ..., v4.4.37].
    - You can only install one version of a package, so only one of these can be installed: symfony/dependency-injection[2.0.4, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.37, v5.0.0, ..., v5.4.3, v6.0.0, v6.0.1, v6.0.2, v6.0.3].
    - contao/calendar-bundle 4.13.0 requires symfony/dependency-injection ^5.4 -> satisfiable by symfony/dependency-injection[v5.4.0, v5.4.1, v5.4.2, v5.4.3].
    - Root composer.json requires inspiredminds/contao-news-categories-search ^1.2 -> satisfiable by inspiredminds/contao-news-categories-search[1.2.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

# Process terminated with exit code 2
# Result: Misuse of shell builtins

`

Nehme ich das Bundle raus, dann läuft das Update problemlos durch.

Vielen Dank und beste Grüße
Sares

**Comment by saress** [comment] 2022-02-18 12:15
Oh sorry, hab den Eintrag bezüglich[ 4.12+](https://github.com/inspiredminds/contao-news-categories-search/issues/1) nicht gesehen, damit dürfte mein Issue wohl hinfällig sein.

**Comment by fritzmg** [comment] 2022-02-18 12:20
Duplicate of #1

**Closed as completed by fritzmg** 2022-02-18 12:20 UTC
